# Generated by Django 4.2.7 on 2025-06-15 10:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("avatars", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("garments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SizeRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recommended_size", models.CharField(max_length=10)),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("alternative_size", models.CharField(blank=True, max_length=10)),
                (
                    "fit_preference",
                    models.CharField(
                        choices=[
                            ("slim", "Slim Fit"),
                            ("regular", "Regular Fit"),
                            ("relaxed", "Relaxed Fit"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                ("user_selected_size", models.CharField(blank=True, max_length=10)),
                (
                    "user_feedback",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("perfect", "Perfect Fit"),
                            ("too_small", "Too Small"),
                            ("too_large", "Too Large"),
                            ("too_short", "Too Short"),
                            ("too_long", "Too Long"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "avatar",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="avatars.avatar",
                    ),
                ),
                (
                    "garment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_recommendations",
                        to="garments.garment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "size_recommendations",
                "indexes": [
                    models.Index(
                        fields=["user"], name="size_recomm_user_id_62a168_idx"
                    ),
                    models.Index(
                        fields=["garment"], name="size_recomm_garment_5bda75_idx"
                    ),
                ],
            },
        ),
    ]
