# Generated by Django 4.2.7 on 2025-06-18 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("garments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("trend_score", models.FloatField()),
                ("adoption_rate", models.FloatField()),
                ("seasonal_relevance", models.JSONField(default=dict)),
                ("demographic_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StyleMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            ("first_outfit", "First Outfit Created"),
                            ("style_evolution", "Style Evolution"),
                            ("sustainability_goal", "Sustainability Goal Reached"),
                            ("brand_diversity", "Brand Diversity Achievement"),
                            ("color_mastery", "Color Combination Mastery"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("achieved_at", models.DateTimeField()),
                ("data", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StyleAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dominant_colors", models.JSONField(default=list)),
                ("color_frequency", models.JSONField(default=dict)),
                ("favorite_color_combinations", models.JSONField(default=list)),
                ("preferred_styles", models.JSONField(default=list)),
                ("style_evolution_timeline", models.JSONField(default=list)),
                ("preferred_fits", models.JSONField(default=dict)),
                ("size_consistency", models.JSONField(default=dict)),
                ("top_brands", models.JSONField(default=list)),
                ("brand_loyalty_score", models.FloatField(default=0.0)),
                ("seasonal_preferences", models.JSONField(default=dict)),
                ("weather_adaptation_score", models.FloatField(default=0.0)),
                ("garment_reuse_rate", models.FloatField(default=0.0)),
                ("cost_per_wear", models.JSONField(default=dict)),
                ("sustainability_score", models.FloatField(default=0.0)),
                ("most_worn_items", models.JSONField(default=list)),
                ("least_worn_items", models.JSONField(default=list)),
                ("outfit_repetition_rate", models.FloatField(default=0.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WearEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_worn", models.DateField()),
                ("occasion", models.CharField(blank=True, max_length=100)),
                ("weather", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
                    ),
                ),
                (
                    "garment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garments.garment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "garment", "date_worn")},
            },
        ),
    ]
