# Test Profile Configuration
spring:
  config:
    activate:
      on-profile: test
  
  # Use H2 in-memory database for testing
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  
  # Initialize schema
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql 
  
  # Disable Redis for testing (use in-memory cache)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000ms
  
  # Disable email for testing
  mail:
    host: localhost
    port: 1025

# Disable mail health check for testing
management:
  health:
    mail:
      enabled: false

# Test-specific configuration
miora:
  ml-service:
    base-url: http://localhost:8000
    timeout: 5s
    retry-attempts: 1
  
  upload:
    max-file-size: 1048576  # 1MB in bytes
    avatar-storage-path: /tmp/miora-test/avatars
    garment-storage-path: /tmp/miora-test/garments
  
  business:
    max-avatars-per-user: 2
    max-garments-per-user: 10

# Logging for testing
logging:
  level:
    com.miora: DEBUG
    org.springframework.security: INFO
    org.springframework.r2dbc: INFO
    org.springframework.web: INFO 