# Generated by Django 4.2.7 on 2025-06-18 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("try_on", "0002_outfittemplate_stylerule_outfitrating"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("joined", "Joined"),
                            ("submitted", "Submitted"),
                            ("completed", "Completed"),
                            ("winner", "Winner"),
                        ],
                        default="joined",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StyleChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("theme", models.CharField(max_length=100)),
                ("required_items", models.JSONField(default=list)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("prizes", models.JSONField(default=dict)),
                (
                    "participants",
                    models.ManyToManyField(
                        through="community.ChallengeParticipation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="OutfitPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.TextField()),
                ("hashtags", models.JSONField(default=list)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("occasion", models.CharField(blank=True, max_length=50)),
                ("likes_count", models.IntegerField(default=0)),
                ("comments_count", models.IntegerField(default=0)),
                ("shares_count", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outfit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="try_on.outfit"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="challengeparticipation",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="community.stylechallenge",
            ),
        ),
        migrations.AddField(
            model_name="challengeparticipation",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="community.outfitpost",
            ),
        ),
        migrations.AddField(
            model_name="challengeparticipation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="challengeparticipation",
            unique_together={("user", "challenge")},
        ),
    ]
