# Generated by Django 4.2.7 on 2025-06-15 10:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("avatars", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("garments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outfit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "privacy_level",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("friends", "Friends Only"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "avatar",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="avatars.avatar",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outfits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "outfits",
            },
        ),
        migrations.CreateModel(
            name="TryOnSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_name", models.CharField(blank=True, max_length=200)),
                (
                    "fit_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("recommended_size", models.CharField(blank=True, max_length=10)),
                (
                    "confidence_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "session_duration_seconds",
                    models.IntegerField(blank=True, null=True),
                ),
                ("viewport_interactions", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "avatar",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tryon_sessions",
                        to="avatars.avatar",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tryon_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tryon_sessions",
            },
        ),
        migrations.CreateModel(
            name="OutfitGarment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "layer_order",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("selected_size", models.CharField(blank=True, max_length=10)),
                (
                    "garment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garments.garment",
                    ),
                ),
                (
                    "outfit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garments",
                        to="try_on.outfit",
                    ),
                ),
            ],
            options={
                "db_table": "outfit_garments",
                "ordering": ["layer_order"],
            },
        ),
        migrations.CreateModel(
            name="TryOnSessionGarment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "layer_order",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("selected_size", models.CharField(blank=True, max_length=10)),
                (
                    "fit_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "garment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garments.garment",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garments",
                        to="try_on.tryonsession",
                    ),
                ),
            ],
            options={
                "db_table": "tryon_session_garments",
                "ordering": ["layer_order"],
                "unique_together": {("session", "layer_order")},
            },
        ),
        migrations.AddIndex(
            model_name="tryonsession",
            index=models.Index(fields=["user"], name="tryon_sessi_user_id_2b5699_idx"),
        ),
        migrations.AddIndex(
            model_name="tryonsession",
            index=models.Index(
                fields=["created_at"], name="tryon_sessi_created_015466_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="outfitgarment",
            unique_together={("outfit", "layer_order")},
        ),
        migrations.AddIndex(
            model_name="outfit",
            index=models.Index(fields=["user"], name="outfits_user_id_4bf0b9_idx"),
        ),
        migrations.AddIndex(
            model_name="outfit",
            index=models.Index(
                fields=["user", "is_favorite"], name="outfits_user_id_794091_idx"
            ),
        ),
    ]
