# Generated by Django 4.2.7 on 2025-06-18 09:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("try_on", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutfitTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("casual", "Casual"),
                            ("business", "Business"),
                            ("formal", "Formal"),
                            ("sport", "Sport"),
                            ("party", "Party"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                            ("autumn", "Autumn"),
                            ("winter", "Winter"),
                            ("all", "All Seasons"),
                        ],
                        max_length=20,
                    ),
                ),
                ("style_tags", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="StyleRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("color_match", "Color Matching"),
                            ("pattern_mix", "Pattern Mixing"),
                            ("formality", "Formality Level"),
                            ("seasonal", "Seasonal Appropriateness"),
                        ],
                        max_length=50,
                    ),
                ),
                ("compatible_items", models.JSONField()),
                ("incompatible_items", models.JSONField()),
                ("confidence_score", models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name="OutfitRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "style_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "fit_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outfit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="try_on.outfit"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
